export default {

    members: 'Members',
    title: 'Members of the centre',
    professors: 'Professors',
    employees: 'Research Associates',
    alumni: 'Former Research Associates',

    prof_bock_name: 'Prof. Dr. rer. nat. Steffen Bock',
    prof_bock_affiliation: 'Center for Music and Filminformatics, University of Applied Sciences Ostwestfalen-Lippe / Hochschule für Musik Detmold',
    prof_bock_vita: '<p>Based on his 1995 dissertation on context-based classification methods of raster and vector data by means of methods of artificial intelligence, Steffen Bock has been studying mathematical-statistical pattern and structure recognition in digital media data and their scientific-cartographic visualization for nearly 20 years now.</p><p>These theoretical works were complemented by a multitude of interdisciplinary projects in the areas of computer graphics/animation, interactive media and media design with his transfer to the Department of Media Production at the University of Applied Sciences Ostwestfalen-Lippe in 2000.</p><p>For several years, he has been interested in the integration of spatial audio reproduction methods and 3D moving images, in particular due to his work at the Erich-Thienhaus-Institute of the Hochschule für Musik Detmold.</p><p>Since April 2013, Prof. Bock, together with Prof. Dr. Aristotelis Hadjakos, heads the Center for Music and Film Informatics at the Hochschule für Musik Detmold and the University of Applied Sciences Ostwestfalen-Lippe.</p>',

    prof_engels_name: 'Prof. Dr. Gregor Engels',
    prof_engels_affiliation: 'Software Quality Lab, Paderborn University',
    prof_engels_vita: '<p>For many years now, Engels&rsquo; research group has been working on the research area of model-based engineering, software architecture, process modeling and software quality assurance.</p><p>Based on the de-facto standard modeling language UML, concepts and methods for defining syntax and semantics of domain-specific languages were developed on the basis of graph transformation rules.</p><p>Within the area of software architecture and software evolution, among other things, solution approaches were developed for the consistent composition of components and the matching of heterogeneous component descriptions.</p><p>This also includes work on interface description languages which are created within the SFB 901 project &ldquo;On-the-Fly Computing&ldquo; and covers both functional as well as non-functional aspects.</p><p>In cooperation with the industrial partner Capgemini (Munich) the service-oriented engineering methodology Quasar Enterprise was defined for enterprise IT architectures. These architectures are characterized by a process layer that orchestrates service components.</p><p>Furthermore, in cooperation with IBM Research Zurich, extensive research regarding process modeling and configuration management of process models was conducted. The focus in the area of software quality assurance lies in research on model-based tests, test automation and quality analysis of software models.</p>',

    prof_grotjahn_name: 'Prof. Dr. Rebecca Grotjahn',
    prof_grotjahn_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Paderborn University',
    prof_grotjahn_vita: '<p>The application of a cultural-historical perspective within the field of musical gender research is one of Rebecca Grotjahn&rsquo;s main areas of academic work. Since 2002, she has been the spokesperson for the Women&rsquo;s and Gender Studies section of the Society for Music Research (GfM) and co-founder of the Jahrbuch Musik und Gender. For many years now, her interest has been based on the fundamental concepts that are underlying music, musical reception and musical historiography. In this context, she has submitted a series of essays specifically for the concept of the term and the category of authorship.</p><p>The musical media history of the 19th century is one of her favourite fields of research. Within the framework of a long-term project on everyday musical history initiated by Grotjahn, she also develops the approach of culture and material culture. Furthermore, she is planning to lead a hybrid edition of the works of Ethel Smyth, which will test the tools developed in Detmold / Paderborn in the context of a complex transmission situation.</p>',

    prof_hadjakos_name: 'Prof. Dr. Aristotelis Hadjakos',
    prof_hadjakos_affiliation: 'Center for Music and Filminformatics, University of Applied Sciences Ostwestfalen-Lippe / Hochschule für Musik Detmold',
    prof_hadjakos_vita: '<p>Prof. Dr. Aristotelis Hadjakos, together with Prof. Dr. Steffen Bock, is the head of the Center for Music and Film Informatics which was founded by the Hochschule für Musik Detmold and the University of Applied Sciences Ostwestfalen-Lippe in April 2013. This is a unique cooperation between a college of music and a university of applied sciences with the aim of establishing a joint research institute.</p><p>Prof. Hadjakos has a background in both computer science and music. He studied Computer Science at the Technische Universität Darmstadt and Piano Pedagogy at the Frankfurt University of Music and Performing Arts (HfMDK). After further artistic studies at the Folkwang University of the Arts, he returned to the Technische Universität Darmstadt, where he did a doctorate on sensorbated motion feedback and a related analysis method.</p><p>His other works and current research interests lie in the field of tangible musical man-machine interaction. He regularly publishes at conferences in the field of music and computer science, such as the NMI (New Interfaces for Musical Expression), the SMC (Sound and Music Computing) and the ICMC (International Computer Music Conference).</p>',

    prof_keil_name: 'Prof. Dr.-Ing. Reinhard Keil',
    prof_keil_affiliation: 'Contextual Informatics, Paderborn University',
    prof_keil_vita: '<p>Reinhard Keil has a total of 20 years of experience in the research and development of everyday infrastructures for cooperative distributed knowledge work. He was a consortium leader of various university and company infrastructure projects and is also involved in projects to support research discourse in human and cultural sciences. He is an expert in e-learning, software ergonomics and computer-assisted cooperative working and learning.</p><p>Prof. Keil&rsquo;s chair of Contextual Informatics at Paderborn University offers numerous concepts and preparatory work in the conception of virtual working environments for co-active cooperation and the identification, structuring and coordination of various research objects and processes. This is documented in more than 70 publications, the publication of 15 books and the publication of the journal, Erwägen Wissen Ethik (EWE).</p><p>Accolades: Wissenschaftlermedaille Buenos Aires (1986), Research Prize Software Ergonomics of the GI, Zurich (1991), Honorary Prize of the Hypo Tyrol Bank of the MeDiDaPrix, Innsbruck (2000), Computerworld Honors Program Laureate, San Francisco (2002), Finalist of the Medielyactic Hoschulpreises Hamburg (2008).</p>',

    prof_meister_name: 'Prof. Dr. Dorothee M. Meister',
    prof_meister_affiliation: 'Media pedagogy and empirical media studies, Paderborn University',
    prof_meister_vita: '<p>Prof. Dr. Dorothee Meister has long-term expert experience in the fields of media and evaluation studies. Dr. Meister is especially focused on media usage behaviour, integration of digital media for educational purposes, and evaluating media educational interventions (Meister 2005, Meister et al. 2007). Within the BMBF project, MeCo-Pflege (Kamin/Meister 2011), Meister devotes herself to the integration of digital media into health care and nursing professions.</p><p>Furthermore, Meister has experiences in various (DFG-) projects which combined and reflected upon qualitative and quantitative research methods (Treumann et. al. 2007). Especially the extensive competences gained in those various projects, which were mostly structured qualitatively and quantitatively, are being used for the current project at ZenMEM. Meister is a member of numerous scientific and practical networks (DgfE, ICA, GMK).</p>',

    prof_mueller_lietzkow_name: 'Prof. Dr. Jörg Müller-Lietzkow',
    prof_mueller_lietzkow_affiliation: 'Media Economics and Media Management, Paderborn University',
    prof_mueller_lietzkow_vita: '<p>Jörg Müller-Lietzkow has been professor for media economics and media management at the Institute of Media Studies at Paderborn University since 2008.</p><p>His research focuses on digital media, mobile media, network policy, strategic media management, new institutional economics and the computer and video game industry. Additionally, he teaches sports economics and communication science.</p><p>Recent research projects deal with mobile media (tablets) and their use and usage in everyday life and work (including digital humanities). In addition to the establishment of GamesLab Paderborn, he has also built an international partnership with the world&rsquo;s leading R.I.T. In addition to his academic work, he regularly advises economy and politics. He has been co-speaker of the cnetz e.V. since 2014.</p>',

    prof_muenzmay_name: 'Prof. Dr. Andreas Münzmay',
    prof_muenzmay_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Paderborn University',
    prof_muenzmay_vita: '',

    prof_oevel_name: 'Prof. Dr. Gudrun Oevel',
    prof_oevel_affiliation: 'Center for Information and Media Technologies (IMT), Paderborn University',
    prof_oevel_vita: '<p>Head of the IMT at Paderborn University, Prof. Dr. Gudrun Oevel focuses on the operation of the University&lsquo;s IT and media infrastructure as well as on their further development against the background of research and teaching as the core processes of a university. For this purpose, the IMT regularly submits projects together with scientists and conducts them jointly.</p><p>Within the project, Gudrun Oevel answers all technical questions as well as questions concerning long-term archiving. Furthermore, she offers many years of experience working with sponsoring institutions and also advises the project with regards to a long-term digital humanities perspective.</p>',

    prof_szwillus_name: 'Prof. Dr. Gerd Szwillus',
    prof_szwillus_affiliation: 'Human-Computer Interaction, Paderborn University',
    prof_szwillus_vita: '<p>Prof. Szwillus has been working in the field of human-computer interaction at the Department of Computer Science of the Faculty of Electrical Engineering, Computer Science and Mathematics at Paderborn University.</p><p>Aspects of modeling in the context of user interfaces are in the foreground, as well as the development of concepts in the area of multi-touch processing. In terms of modeling, his focus has been on the early phases, for instance on task analysis and task modeling.</p><p>Computer-aided application domains in particular require an intensive and systematic analysis of processes during the management of tasks (especially the navigation concepts used) and the intuitively usable and understandable structuring of workflows of application software. For this purpose, Szwillus and his research group develop model-based development methods that allow the user interface to be explicitly designed for user tasks.</p><p>The focus of Prof. Szwillus also includes the development of applications for multi-touch tables (MTT) as well as appropriate so-called natural user interfaces for this purpose.</p><p>In the near future, the group will therefore work on the integration of MTT interaction into classical dialog modeling methods, so that a realistic prototyping of natural user interfaces at/on the MTT is made possible. At the same time, the collaborative aspect of the work on the MTT will be incorporated into the task modeling concepts in order to provide the best possible support for joint work.</p>',

    prof_veit_name: 'Prof. Dr. Joachim Veit',
    prof_veit_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Paderborn University',
    prof_veit_vita: '<p>As founder of the project, Prof. Dr. Joachim Veit coordinates the content as well as the organisation and supports the project with his many years of experience in the field of digital music. Under his leadership, the Musikwissenschaftliches Seminar Detmold / Paderborn has gained international acclaim in the area of developing digital techniques for the musicological and editorial field.</p><p>Several conferences (e.g. Paderborn 2007), regularly held summer schools in the area of Digital Humanities (since 2010), workshops and presentations complement the activities that produce a continuously rising number of requests in form of consultations or specific requests for collaborations from the international academic community.</p><p>Veit is a member of the founding board of the new association Digital Humanities in the German-speaking world (DHd) and was involved in the conceptualization of the professionalization area Digital Music Edition in the MA programme Musicology at Paderborn University.</p>',
};