export default {

    members: 'Mitglieder',
    title: 'Mitglieder des Zentrums',
    professors: 'Professor*innen',
    employees: 'Mitarbeiter*innen',
    alumni: 'Ehemalige Mitarbeiter*innen',

    prof_bock_name: 'Prof. Dr. rer. nat. Steffen Bock',
    prof_bock_affiliation: 'Zentrum für Musik- und Filminformatik, Hochschule Ostwestfalen-Lippe / Hochschule für Musik Detmold',
    prof_bock_vita: '<p>Ausgehend von seiner Dissertation über kontextbasierte Klassifikationsverfahren von Raster- und Vektordaten mittels Verfahren der künstlichen Intelligenz aus dem Jahr 1995 beschäftigt sich Steffen Bock seit nunmehr fast 20 Jahren mit der mathematisch-statistischen Muster- und Strukturerkennung in digitalen Mediendaten und deren wissenschaftlich-kartographischer Visualisierung. Mit seinem Wechsel an die Hochschule Ostwestfalen-Lippe in den dortigen Fachbereich Medienproduktion im Jahr 2000 wurden diese theoretischen Arbeiten um eine Vielzahl von interdisziplinären Projekten aus den Bereichen Computergrafik/Animation, Interaktive Medien und Mediendesign ergänzt.</p><p>Seit einigen Jahren, insbesondere durch seine Tätigkeit am Erich-Thienhaus-Institut der Hochschule für Musik Detmold, liegt sein Interessengebiet in der Integration von räumlichen Audiowiedergabeverfahren und 3D-Bewegtbild.</p><p>Seit April 2013 leitet Prof. Bock zusammen mit Prof. Dr. Aristotelis Hadjakos das Zentrum für Musik- und Filminformatik der Hochschule für Musik Detmold und der Hochschule Ostwestfalen-Lippe.</p>',


    prof_engels_name: 'Prof. Dr. Gregor Engels',
    prof_engels_affiliation: 'Software Quality Lab, Universität Paderborn',
    prof_engels_vita: '<p>Die Arbeitsgruppe Engels beschäftigt sich seit vielen Jahren u. a. mit den Forschungsgebieten der modellbasierten Entwicklung, der Softwarearchitektur, der Prozessmodellierung und der Software-Qualitätssicherung. Auf Basis der de-facto Standardmodellierungssprache UML wurden Konzepte und Methoden zur Definition von Syntax und Semantik von domänen-spezifischen Sprachen auf der Basis von Graphtransformationsregeln entwickelt. Im Bereich der Softwarearchitektur und evolution sind u. a. Lösungsansätze für die konsistente Komposition von Komponenten und das Matching von heterogenen Komponentenbeschreibungen entstanden. Hierzu gehören auch Arbeiten zu Schnittstellenbeschreibungssprachen, die sowohl funktionale als auch nicht-funktionale Aspekte umfassen und im Rahmen des SFB 901 "On-the-Fly Computing" entstehen. In Kooperation mit dem industriellen Partner Capgemini, München, wurde die serviceorientierte Entwicklungsmethodik Quasar Enterprise für Enterprise IT-Architekturen definiert. Diese Architekturen zeichnen sich durch eine Prozessschicht aus, mit der Servicekomponenten orchestriert werden.</p><p>In Kooperation mit IBM Research Zürich wurden umfangreiche Forschungsarbeiten zur Prozessmodellierung und zum Konfigurationsmanagement von Prozessmodellen durchgeführt. Schwerpunkt im Bereich der Software-Qualitätssicherung sind insbesondere Arbeiten im modellbasierten Testen, der Testautomatisierung und der Qualitätsanalyse von Software-Modellen.</p>',

    prof_grotjahn_name: 'Prof. Dr. Rebecca Grotjahn',
    prof_grotjahn_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Universität Paderborn',
    prof_grotjahn_vita: '<p>Die Anwendung einer kulturgeschichtlichen Perspektive auf den Bereich der musikalischen Genderforschung bildet einen der Arbeitsschwerpunkte von Rebecca Grotjahn, die seit 2002 Sprecherin der Fachgruppe Frauen- und Genderstudien in der Gesellschaft für Musikforschung und außerdem Mitbegründerin des Jahrbuchs Musik und Gender ist. Seit einigen Jahren gilt ihr Interesse den grundsätzlichen Konzepten, die dem Musizieren, der musikalischen Rezeption und Musikgeschichtsschreibung zugrunde liegen. In diesem Kontext hat sie speziell zum Werkbegriff und der Kategorie Autorschaft eine Reihe von Aufsätzen vorgelegt.</p><p>Die musikalische Mediengeschichte des 19. Jahrhunderts zählt zu ihren bevorzugten Forschungsgebieten. Im Rahmen eines von ihr mit initiierten Langzeitprojekts zur musikalischen Alltagsgeschichte erarbeitet sie sich auch den Ansatz Materielle Kultur und Kultur. Im Planungszustand befindet sich ferner eine von ihr geleitete Hybrid-Ausgabe der Werke Ethel Smyth, in der die in Detmold/Paderborn entwickelten Werkzeuge im Bereich einer komplexen Überlieferungslage zu erproben sind.</p>',

    prof_hadjakos_name: 'Prof. Dr. Aristotelis Hadjakos',
    prof_hadjakos_affiliation: 'Zentrum für Musik- und Filminformatik, Hochschule Ostwestfalen-Lippe / Hochschule für Musik Detmold',
    prof_hadjakos_vita: '<p>Prof. Dr. Aristotelis Hadjakos leitet zusammen mit Prof. Dr. Steffen Bock das gemeinsam von der Hochschule für Musik Detmold und der Hochschule Ostwestfalen-Lippe im April 2013 gegründete Zentrum für Musik- und Filminformatik. Dabei handelt es sich um eine einzigartige Kooperation zwischen einer Musikhochschule und einer Fachhochschule mit dem Ziel ein gemeinsames Forschungsinstitut zu etablieren.</p><p>Prof. Hadjakos hat sowohl in der Informatik als auch in der Musik einen fundierten Hintergrund. Er studierte parallel Informatik an der Technische Universität Darmstadt und Klavierpädagogik an der Hochschule für Musik und Darstellende Kunst Frankfurt am Main. Nach weiterführenden künstlerischen Studien an der Folkwang Hochschule Essen kehrte er an die Technische Universität Darmstadt zurück, wo er über sensorbasiertes Bewegungsfeedback und ein damit verbundenes Analyseverfahren promovierte.</p><p>Seine weiteren Arbeiten und aktuellen Forschungsinteressen liegen im Bereich der be-greifbaren musikalischen Mensch-Maschine-Interaktion. Er publiziert regelmäßig auf Konferenzen im Spannungsfeld Musik und Informatik wie der NIME (New Interfaces for Musical Expression), der SMC (Sound and Music Computing) und der ICMC (International Computer Music Conference).</p>',

    prof_keil_name: 'Prof. Dr.-Ing. Reinhard Keil',
    prof_keil_affiliation: 'Kontextuelle Informatik, Universität Paderborn',
    prof_keil_vita: '<p>Prof. Keil verfügt über eine 20-jährige Erfahrung im Bereich der Erforschung und Entwicklung von alltagstauglichen Infrastrukturen für die kooperative verteilte Wissensarbeit. Er war Konsortialleiter verschiedener universitärer und betrieblicher Inftrastrukturprojekte und ist als Informatiker auch an Projekten zur Unterstützung des Forschungsdiskurses in den Human- und den Kulturwissenschaften beteiligt. Er ist Experte für E-Learning, Software-Ergonomie und computerunterstütztes kooperatives Arbeiten und Lernen.</p><p>Bei der Konzeption virtueller Arbeitsumgebungen zur ko-aktiven Zusammenarbeit und der Identifizierung, Strukturierung und Koordination unterschiedlichster Forschungsgegenstände und -prozesse, wie sie im beantragten Zentrum gefordert werden, gibt es am Lehrstuhl Kontextuelle Informatik von Prof. Keil bereits zahlreiche Konzepte und Vorarbeiten. Dies dokumentiert sich in über 70 Veröffentlichungen, der Herausgeberschaft von 15 Büchern und der Zeitschrift Erwägen Wissen Ethik.</p><p>Auszeichnungen: Wissenschaftlermedaille Buenos Aires (1986), Forschungspreis Software-Ergonomie der GI, Zürich (1991), Ehrenpreis der Hypo Tyrol Bank des MeDiDaPrix, Innsbruck (2000), Computerworld Honors Program Laureate, San Francisco (2002), Finalist des Mediendidaktischen Hoschulpreises Hamburg (2008).</p>',

    prof_meister_name: 'Prof. Dr. Dorothee M. Meister',
    prof_meister_affiliation: 'Medienpädagogik und empirische Medienforschung, Universität Paderborn',
    prof_meister_vita: '<p>Prof. Dr. Dorothee Meister (Universität Paderborn) verfügt über langjährige Erfahrungen in der Medien- und Evaluationsforschung. Die Schwerpunkte Mediennutzungsverhalten, Integration digitaler Medien in Bildungskontexte sowie Evaluation von medienpädagogischen Interventionen sind in diesem Kontext besonders herauszustellen (Meister 2005, Meister et al. 2007). Aktuell widmet sich Frau Meister im BMBF-Projekt MeCo-Pflege der Integration digitaler Medien in Pflegeberufen (Kamin/Meister 2011).</p><p>Zudem verfügt sie über Erfahrungen in (DFG-)Projekten, in denen qualitative und quantitative Methoden kompiniert und reflektiert wurden (Treumann et. al. 2007). Gerade die umfangreichen Kompetenzen in den verschiedenen Projekten, die meist sowohl quantitativ als auch qualitativ angelegt waren, werden in das geplante Vorhaben eingebracht. Darüber hinaus ist sie Mitglied zahlreicher Wissenschafts- und Praxisnetzwerke (DGfE, ICA, GMK).</p>',

    prof_mueller_lietzkow_name: 'Prof. Dr. Jörg Müller-Lietzkow',
    prof_mueller_lietzkow_affiliation: 'Medienökonomie und Medienmanagement, Universität Paderborn',
    prof_mueller_lietzkow_vita: '<p>Jörg Müller-Lietzkow, Prof. Dr. rer. oec., geboren 1970, seit 2008 Professor für Medienökonomie und Medienmanagement am Institut für Medienwissenschaften der Universität Paderborn.</p><p>Seine Forschungsschwerpunkte konzentrieren sich auf die digitale Medienwirtschaft, mobile Medien, Netzpolitik, strategisches Medienmanagement, neue Institutionenökonomie sowie die Computer- und Videospielindustrie. In der Lehre vertritt er zusätzlich Sportökonomie sowie Kommunikationswissenschaft.</p><p>Neuere Forschungsprojekte beschäftigen sich mit mobilen Medien (Tablets) und deren Anwendung im Alltag und Beruf (inkl. Digital Humanities). Im Bereich der Gamesausbildung hat er neben dem GamesLab Paderborn auch eine internationale Partnerschaft zum weltweit führenden R.I.T. aufgebaut und etabliert. Neben seiner akademischen Tätigkeit berät er regelmäßig Wirtschaft und Politik. Er ist seit Januar 2014 Co-Sprecher des cnetz e.V.</p>',

    prof_muenzmay_name: 'Prof. Dr. Andreas Münzmay',
    prof_muenzmay_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Universität Paderborn',
    prof_muenzmay_vita: '<p>Andreas Münzmay ist als Professor für Musikwissenschaft/Digitale Musikedition/Digital Humanities an der Universität Paderborn Geschäftsführender Leiter des Musikwissenschaftlichen Seminars Detmold/Paderborn und als Akademie-Professor beteiligt am Langzeitvorhaben Beethovens Werkstatt: Genetische Textkritik und Digitale Musikedition der Akademie der Wissenschaften und der Literatur Mainz.</p><p>Sein DH-Forschungsschwerpunkt betrifft die Theorie und Praxis digitaler Musikedition und verbindet sich mit seiner breiten kultur- und musikwissenschaftlichen Expertise insbesondere im Bereich des Musiktheaters und der Librettologie, der Improvisation und des Jazz sowie der Mediengeschichte der Musik.</p><p>Münzmay ist Mitglied im Vorstand der Gesellschaft der Musikforschung und u.a. im Beirat des Forschungsinformationsdienstes (FID) Musik. 2012 erhielt er für seine wissenschaftlichen Leistungen den Hermann-Abert-Preis der Gesellschaft für Musikforschung.</p>',

    prof_oevel_name: 'Prof. Dr. Gudrun Oevel',
    prof_oevel_affiliation: 'Zentrum für Informations- und Medientechnologien, Universität Paderborn',
    prof_oevel_vita: '<p>Als Leiterin des IMT stehen für Prof. Dr. Gudrun Oevel nicht nur der Betrieb der IT- und Medieninfrastruktur für die Universität Paderborn im Fokus sondern insbesondere deren Weiterentwicklung vor dem Hintergrund von Forschung und Lehre als Kernprozesse einer Hochschule. Dazu beantragt das IMT regelmäßig Projekte gemeinsam mit Wissenschaftlerinnen und Wissenschaftlern und führt diese gemeinsam durch.</p><p>Im Projekt steht Gudrun Oevel für alle technischen Fragestellungen sowie Fragen rund um die Langzeitarchivierung zur Verfügung. Zusätzlich bringt sie ihre langjährige Erfahrungen in der Zusammenarbeit mit Förderinstitutionen ein und berät das Projekt im Hinblick auf eine längerfristige Digital Humanities-Perspektive.</p>',

    prof_szwillus_name: 'Prof. Dr. Gerd Szwillus',
    prof_szwillus_affiliation: 'Mensch-Computer-Interaktion, Universität Paderborn',
    prof_szwillus_vita: '<p>Prof. Szwillus arbeitet seit Jahren im Bereich Mensch-Computer-Interaktion am Institut für Informatik der Fakultät für Elektrotechnik, Informatik und Mathematik der Universität Paderborn. Dabei stehen Aspekte der Modellierung im Kontext von Benutzungsschnittstellen im Vordergrund, aber auch Entwicklung von Konzepten im Bereich Multi-Touch werden bearbeitet. Bezogen auf Modellierung hat sich sein Arbeitsschwerpunkt auf die frühen Phasen, also auf Aufgabenanalyse und Aufgabenmodellierung fokussiert. Gerade computerferne Anwendungsdomänen erfordern eine intensive und systematische Analyse von Abläufen bei der Aufgabenbearbeitung (vor allem der eingesetzten Navigationskonzepte) und die intuitiv benutz- und verstehbare Strukturierung von Arbeitsabläufen von Anwendungssoftware. Hierzu werden in der AG Szwillus modellbasierte Entwicklungsmethoden erarbeitet, die es erlauben, die Gestaltung von Bedienoberflächen explizit an Benutzeraufgaben zu orientieren.</p><p>Zu den Schwerpunkten von Prof. Szwillus gehört auch die Entwicklung von Anwendungen für Multi-Touch-Tische (MTT) sowie angemessener "natürlicher" Benutzerschnittstellen ("Natural User Interfaces") hierfür. In der nächsten Zeit wird in der Fachgruppe daher an der Integration von MTT-Interaktion in klassische Dialogmodellierungsmethoden gearbeitet werden, sodass ein realistisches Prototyping von sogenannten "Natural User Interfaces" am MTT ermöglicht wird. Gleichzeitig wird der kollaborative Aspekt der Arbeit am MTT in die Aufgabenmodellierungskonzepte einfließen, um gemeinsames Arbeiten bestmöglich unterstützen zu können.</p>',

    prof_veit_name: 'Prof. Dr. Joachim Veit',
    prof_veit_affiliation: 'Musikwissenschaftliches Seminar Detmold/Paderborn, Universität Paderborn',
    prof_veit_vita: '<p>Als Initiator des Gesamtprojekts koordiniert Prof. Dr. Joachim Veit sowohl die inhaltliche als auch die organisatorische Seite und bringt seine jahrelang gewonnenen Erfahrungen auf dem Gebiet der digitalen Musikedition ein. Unter seiner Leitung hat sich das Muwi Detmold/Paderborn auf dem Gebiet der Erschließung digitaler Techniken für den musikwissenschaftlich-editorischen Bereich international profiliert.</p><p>Eigene Tagungen (u. a. Paderborn 2007), regelmäßige Summerschools im Bereich der Digital Humanities (seit 2010), Workshops und Präsentatonen ergänzen die Aktivitäten, aus denen eine stetig zunehmende Zahl von Anfragen, Beratungsgesprächen oder konkreten Bitten um Zusammenarbeit aus der wissenschaftlichen Community im In- und Ausland resultiert. Veit ist Mitglied im Gründungsvorstand des neuen Verbunds Digital Humanities im deutschsprachigen Raum (DHd) und war an der Konzeption des Professionalisierungsbereichs Digitale Musikedition im MA-Studiengang Musikwissenschaft der Universität Paderborn beteiligt.</p>',

};